/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { CollectionService } from "../collection.service";
import { CollectionCreateInput } from "./CollectionCreateInput";
import { CollectionWhereInput } from "./CollectionWhereInput";
import { CollectionWhereUniqueInput } from "./CollectionWhereUniqueInput";
import { CollectionFindManyArgs } from "./CollectionFindManyArgs";
import { CollectionUpdateInput } from "./CollectionUpdateInput";
import { Collection } from "./Collection";
import { RecordFindManyArgs } from "../../record/base/RecordFindManyArgs";
import { Record } from "../../record/base/Record";
import { RecordWhereUniqueInput } from "../../record/base/RecordWhereUniqueInput";

export class CollectionGrpcControllerBase {
  constructor(protected readonly service: CollectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Collection })
  @GrpcMethod("CollectionService", "createCollection")
  async createCollection(
    @common.Body() data: CollectionCreateInput
  ): Promise<Collection> {
    return await this.service.createCollection({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        slug: true,
        structure: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Collection] })
  @ApiNestedQuery(CollectionFindManyArgs)
  @GrpcMethod("CollectionService", "collections")
  async collections(@common.Req() request: Request): Promise<Collection[]> {
    const args = plainToClass(CollectionFindManyArgs, request.query);
    return this.service.collections({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        slug: true,
        structure: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Collection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CollectionService", "collection")
  async collection(
    @common.Param() params: CollectionWhereUniqueInput
  ): Promise<Collection | null> {
    const result = await this.service.collection({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        slug: true,
        structure: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Collection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CollectionService", "updateCollection")
  async updateCollection(
    @common.Param() params: CollectionWhereUniqueInput,
    @common.Body() data: CollectionUpdateInput
  ): Promise<Collection | null> {
    try {
      return await this.service.updateCollection({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          slug: true,
          structure: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Collection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CollectionService", "deleteCollection")
  async deleteCollection(
    @common.Param() params: CollectionWhereUniqueInput
  ): Promise<Collection | null> {
    try {
      return await this.service.deleteCollection({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          slug: true,
          structure: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/records")
  @ApiNestedQuery(RecordFindManyArgs)
  @GrpcMethod("CollectionService", "findManyRecords")
  async findManyRecords(
    @common.Req() request: Request,
    @common.Param() params: CollectionWhereUniqueInput
  ): Promise<Record[]> {
    const query = plainToClass(RecordFindManyArgs, request.query);
    const results = await this.service.findRecords(params.id, {
      ...query,
      select: {
        collection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/records")
  @GrpcMethod("CollectionService", "connectRecords")
  async connectRecords(
    @common.Param() params: CollectionWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        connect: body,
      },
    };
    await this.service.updateCollection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/records")
  @GrpcMethod("CollectionService", "updateRecords")
  async updateRecords(
    @common.Param() params: CollectionWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        set: body,
      },
    };
    await this.service.updateCollection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/records")
  @GrpcMethod("CollectionService", "disconnectRecords")
  async disconnectRecords(
    @common.Param() params: CollectionWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        disconnect: body,
      },
    };
    await this.service.updateCollection({
      where: params,
      data,
      select: { id: true },
    });
  }
}
